In [89]:
from google.colab import drive

drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [90]:
import pandas as pd
import numpy as np

In [91]:
df = pd.read_csv('/content/drive/My Drive/Colab Notebooks/bengaluru.csv')
df

PM2.5   PM10     NO    NO2    NOx    NH3     CO    SO2     O3  Benzene  \
0       NaN    NaN   3.26  17.33  10.88  20.36   0.33   3.54  10.73     0.56   
1       NaN    NaN   6.05  19.73  14.14  23.74   1.35   3.97  22.77     0.65   
2       NaN    NaN  11.91  19.88  20.72   4.32  17.40  13.61  12.03     0.53   
3       NaN    NaN   7.45  21.61  16.88   0.87   5.05   6.52  17.70     0.55   
4       NaN    NaN   9.52  22.17  21.76  31.38   1.83   4.71  12.72     0.40   
...     ...    ...    ...    ...    ...    ...    ...    ...    ...      ...   
2004  16.60  29.48   3.06  13.68  13.07   6.88   0.67   7.29  15.69     0.21   
2005  20.44  26.34   2.69  10.33  10.58   6.58   0.66   6.60  17.59     0.12   
2006  28.68  29.27   3.62  12.12  12.94   6.80   0.56   6.33  16.99     0.17   
2007  14.47  24.26   4.61  12.69  15.00   6.82   0.56   6.45  16.08     0.18   
2008  17.50  30.48   3.95  13.25  14.83   7.42   0.54   6.66  15.40     0.27   

      Toluene   AQI  
0        4.64   NaN  
1        5.31   NaN  
2       19.25   NaN  
3        7.47   NaN  
4        4.36   NaN  
...       ...   ...  
2004     1.18  51.0  
2005     0.94  61.0  
2006     1.17  65.0  
2007     0.86  63.0  
2008     0.65  43.0  

[2009 rows x 12 columns]

In [92]:
dataset = df.values
dataset

array([[  nan,   nan,  3.26, ...,  0.56,  4.64,   nan],
       [  nan,   nan,  6.05, ...,  0.65,  5.31,   nan],
       [  nan,   nan, 11.91, ...,  0.53, 19.25,   nan],
       ...,
       [28.68, 29.27,  3.62, ...,  0.17,  1.17, 65.  ],
       [14.47, 24.26,  4.61, ...,  0.18,  0.86, 63.  ],
       [17.5 , 30.48,  3.95, ...,  0.27,  0.65, 43.  ]])

In [93]:
x = dataset[:,0:11]
y = dataset[:,11]

In [ ]:
x

array([[  nan,   nan,  3.26, ..., 10.73,  0.56,  4.64],
       [  nan,   nan,  6.05, ..., 22.77,  0.65,  5.31],
       [  nan,   nan, 11.91, ..., 12.03,  0.53, 19.25],
       ...,
       [28.68, 29.27,  3.62, ..., 16.99,  0.17,  1.17],
       [14.47, 24.26,  4.61, ..., 16.08,  0.18,  0.86],
       [17.5 , 30.48,  3.95, ..., 15.4 ,  0.27,  0.65]])

In [ ]:
y

array([nan, nan, nan, ..., 65., 63., 43.])

In [ ]:
from sklearn import preprocessing
min_max_scaler = preprocessing.MinMaxScaler()
x_scale = min_max_scaler.fit_transform(x)

In [94]:
def to_supervised(train):
  window_size = 3
  x = []
  y = []
  for i in range(window_size, len(train)):
    x.append(train[i-window_size:i,:])
    y.append(train[i,0:1])

  return x,y

In [95]:
x, y = to_supervised(x_scale)
x = np.array(x)
y = np.array(y)
print('Y' ,y.shape)
print('X' ,x.shape)

Y (2006, 1)
X (2006, 3, 11)


In [ ]:
#from sklearn.model_selection import train_test_split
#x_train, x_val_and_test, y_train, y_val_and_test = train_test_split(x_scale, y, test_size=0.3)
#x_val, x_test, y_val, y_test = train_test_split(x_val_and_test, y_val_and_test, test_size=0.5)
#print(x_train.shape, x_val.shape, x_test.shape, y_train.shape, y_val.shape, y_test.shape)

In [96]:
#Splitting the dataset
n_train = 24*365
x_train, x_test = x[n_train:,] , x[:n_train,]


y_train, y_test =y[n_train:,] , y[:n_train,]


In [104]:
x_train.shape
y

(0, 3, 11)

In [102]:
from keras.models import Sequential
from keras.layers import Dense,Dropout,LSTM
model = Sequential()

model.add(LSTM(units = 50, return_sequences = True, input_shape=(x_train.shape[1], x_train.shape[2])))
model.add(Dropout(0.2))

model.add(LSTM(units = 50, return_sequences = True))
model.add(Dropout(0.2))

model.add(LSTM(units = 50))
model.add(Dropout(0.2))

model.add(Dense(units = 1))

model.compile(optimizer = 'adam', loss = 'mean_squared_error', metrics=['accuracy'])


In [103]:
model.fit(x_train, y_train, epochs = 20, batch_size = 32)

Epoch 1/20


ValueError: ignored